{% set name = "bonnndit" %}
{% set version = "0.2.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4c84d9c69a87ac33619cb34039f8758ff4b798f6f5d65788d758795bc6af6e45

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - findblas
    - numpy
  run:
    - python
    - dipy
    - nibabel
    - numpy
    - tqdm
    - cvxopt
    - mpmath
    - plyfile
    - pynrrd

test:
  imports:
    - bonndit
    - bonndit.deconv
    - bonndit.directions
    - bonndit.filter
    - bonndit.pmodels
    - bonndit.tracking
    - bonndit.tracking.kalman
    - bonndit.utilc
    - bonndit.utils
  requires:
    - cvxopt
    - dipy
    - mpmath
    - nibabel
    - numpy
    - pynrrd
    - pytest
    - scipy
    - tqdm

about:
  home: "https://github.com/MedVisBonn/bonndit"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: 
  summary: "The bonndit package contains the latest diffusion imaging tools developed at the University of Bonn."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
