package:
  name: bonndit
  version: 0.2.0

source:
 #git_rev: https://github.com/MedVisBonn/bonndit/releases/latest
  git_url: https://github.com/MedVisBonn/bonndit.git

build:
  preserve_egg_dir: True


requirements:
  build:
    - python
    - setuptools
    - Cython
    - numpy {{ numpy }}
    - findblas
    - wheel
  run:
    - python
    - nibabel
    - numpy
    - pandas
    - scipy
    - tqdm
    - cvxopt
    - mpmath
    - plyfile
    - Cython
    - pynrrd
    - dipy

about:
  home: https://github.com/MedVisBonn/bonndit
  summary: "Latest dMRI software from University of Bonn"
  license: GPL