package:
  name: bonndit
  version: 0.2.1

source:
  path: ./

build:
  preserve_egg_dir: True




requirements:
  build:
    - python
    - Cython
    - numpy <1.24
    - findblas
  run:
    - python
    - nibabel
    - numpy <1.24
    - pandas
    - scipy
    - tqdm
    - cvxopt
    - findblas
    - mpmath
    - plyfile
    - Cython
    - pynrrd
    - dipy

test:
  imports:
    - bonndit
    - bonndit.utils
  requires:
    - cvxopt
    - dipy
    - mpmath
    - nibabel
    - numpy
    - pytest
    - scipy
    - tqdm

about:
  home: ./
  summary: "Latest dMRI software from University of Bonn"
  license: GPL