package:
  name: bonndit
  version: 0.2.1

source:
  path: ./
  #fn: v0.2.1
  #url: https://github.com/MedVisBonn/bonndit/archive/refs/tags/v0.2.1.tar.gz
  #git_url: https://github.com/MedVisBonn/bonndit.git

build:
  preserve_egg_dir: True


requirements:
  build:
    - python
    - Cython
    - numpy {{ numpy }}
    - findblas
  run:
    - python
    - nibabel
    - numpy {{ numpy }}
    - pandas
    - scipy
    - tqdm
    - cvxopt
    - mpmath
    - plyfile
    - Cython
    - pynrrd
    - dipy

about:
  home: https://github.com/MedVisBonn/bonndit
  summary: "Latest dMRI software from University of Bonn"
  license: GPL