{% set name = "bonndit" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 57e2aadfde04d0b74f665aeac28bd35f9f3e6bd1062b8f26f578baaf2a3c0754

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cvxopt
    - dipy
    - mpmath
    - nibabel
    - numpy
    - pandas
    - pip
    - python
    - scipy
    - tqdm
  run:
    - cvxopt
    - dipy
    - mpmath
    - nibabel
    - numpy
    - pandas
    - python
    - scipy
    - tqdm

test:
  imports:
    - bonndit
    - bonndit.michi
  requires:
    - cvxopt
    - dipy
    - mpmath
    - nibabel
    - numpy
    - pytest
    - scipy
    - tqdm

about:
  home: "https://github.com/MedVisBonn/bonndit"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: 
  summary: "The bonndit package contains the latest diffusion imaging tools developed at the University of Bonn."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
