name: Publish to conda

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Install OpenBLAS by apt
      run: |
        apt update
        apt install -y libopenblas-dev

    - name: publish-to-conda
      uses: JoGruen/publish_conda_package_action@1.0.1
      with:
        # CondaDir: locate the directory containing your meta.yml, conda_build_config.yaml (...) files
        CondaDir: './'
        # Channels: You can add more channel with a space separator
        Channels: 'conda-forge xderes'
        # Platforms: remove one or more of these platforms
        Platforms: 'linux-64'
        CondaToken: ${{ secrets.CondaToken }}
